AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: 'with_fixed_indentation'

Style/Documentation:
  Enabled: false